/**
 * One-off nearby_slugs backfill SQL generator. Ports the logic from
 * scripts/generate-nearby-backfill.ts to a Vercel-hosted route so it
 * runs against the project's existing Supabase env vars.
 *
 * Auth: header `x-audit-key` must match AUDIT_KEY constant below. Hardcoded
 * for a one-time run; the route is removed in a follow-up commit.
 *
 * Returns a SQL file as text/plain for piping straight into Supabase.
 *
 * Read-only on Supabase. The user runs the resulting SQL manually.
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

const AUDIT_KEY = "28173fff6dd3726d49d7f6db42e89388a7dbc8d7f5caf9da";

const MAX_NEARBY = 6;
const SAME_DEST_RADIUS_KM = 10;
const NO_DEST_RADIUS_KM = 15;
const MIN_PROXIMITY_RESULTS = 4;

interface PlaceRow {
  slug: string;
  title: string;
  destination: string | null;
  featured: boolean | null;
  sort_order: number | null;
  latitude: number | null;
  longitude: number | null;
  nearby_slugs: string[] | null;
}

function haversineKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLon = toRad(lon2 - lon1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

function sortSiblings(a: PlaceRow, b: PlaceRow): number {
  const af = a.featured ? 1 : 0;
  const bf = b.featured ? 1 : 0;
  if (af !== bf) return bf - af;
  const aso = a.sort_order ?? Number.MAX_SAFE_INTEGER;
  const bso = b.sort_order ?? Number.MAX_SAFE_INTEGER;
  if (aso !== bso) return aso - bso;
  return a.title.localeCompare(b.title);
}

function pickNearby(target: PlaceRow, all: PlaceRow[]): string[] {
  const others = all.filter((p) => p.slug !== target.slug);
  const targetDest = (target.destination || "").trim().toLowerCase();
  const hasCoords = target.latitude != null && target.longitude != null;

  if (!targetDest && !hasCoords) return [];

  if (targetDest) {
    const sameDest = others
      .filter((p) => (p.destination || "").trim().toLowerCase() === targetDest)
      .sort(sortSiblings);

    if (hasCoords) {
      const withinRadius = sameDest.filter((p) => {
        if (p.latitude == null || p.longitude == null) return false;
        return haversineKm(target.latitude!, target.longitude!, p.latitude, p.longitude) <= SAME_DEST_RADIUS_KM;
      });
      if (withinRadius.length >= MIN_PROXIMITY_RESULTS) {
        return withinRadius.slice(0, MAX_NEARBY).map((p) => p.slug);
      }
    }
    return sameDest.slice(0, MAX_NEARBY).map((p) => p.slug);
  }

  const withCoords = others.filter((p) => p.latitude != null && p.longitude != null);
  const ranked = withCoords
    .map((p) => ({
      slug: p.slug,
      dist: haversineKm(target.latitude!, target.longitude!, p.latitude!, p.longitude!),
    }))
    .filter((r) => r.dist <= NO_DEST_RADIUS_KM)
    .sort((a, b) => a.dist - b.dist);

  return ranked.slice(0, MAX_NEARBY).map((r) => r.slug);
}

function escapeSqlString(s: string): string {
  return s.replace(/'/g, "''");
}

function arrayLiteral(slugs: string[]): string {
  if (slugs.length === 0) return "'{}'::text[]";
  return `ARRAY[${slugs.map((s) => `'${escapeSqlString(s)}'`).join(", ")}]::text[]`;
}

export async function GET(req: NextRequest) {
  if (req.headers.get("x-audit-key") !== AUDIT_KEY) {
    return NextResponse.json({ error: "unauthorised" }, { status: 401, headers: { "x-robots-tag": "noindex" } });
  }
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) {
    return NextResponse.json({ error: "Supabase env not configured" }, { status: 500, headers: { "x-robots-tag": "noindex" } });
  }

  const sb = createClient(url, key, { auth: { persistSession: false } });
  const { data, error } = await sb
    .from("places")
    .select("slug, title, destination, featured, sort_order, latitude, longitude, nearby_slugs")
    .eq("published", true);

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500, headers: { "x-robots-tag": "noindex" } });
  }

  const places = (data || []) as PlaceRow[];
  const targets = places.filter((p) => !p.nearby_slugs || p.nearby_slugs.length === 0);

  const lines: string[] = [
    "-- Backfill nearby_slugs for published places.",
    "-- Generated by /api/admin/generate-nearby-backfill",
    "-- Skips places that already have nearby_slugs populated.",
    "-- Review before running.",
    "--",
    `-- ${places.length} published places · ${targets.length} need backfill`,
    "",
    "BEGIN;",
    "",
  ];

  let updateCount = 0;
  let emptyCount = 0;
  for (const target of targets) {
    const slugs = pickNearby(target, places);
    if (slugs.length === 0) emptyCount += 1;
    lines.push(
      `UPDATE places SET nearby_slugs = ${arrayLiteral(slugs)} WHERE slug = '${escapeSqlString(target.slug)}';`,
    );
    updateCount += 1;
  }

  lines.push("");
  lines.push("COMMIT;");
  lines.push("");
  lines.push(`-- ${updateCount} UPDATE statements (${updateCount - emptyCount} populated, ${emptyCount} empty — no destination + no coords).`);
  lines.push("");

  return new NextResponse(lines.join("\n"), {
    status: 200,
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "cache-control": "no-store",
      "x-robots-tag": "noindex",
      "content-disposition": `inline; filename="backfill-nearby-slugs.sql"`,
    },
  });
}
